language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev --no-interaction install
    - sudo apt-get install

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq golang git libgtk-3-dev libgtkspell-3-dev libtspi-dev trousers tor mercurial pkg-config libgtkspell-3-0 libgtkspell0

install:
  - export GOPATH=$TRAVIS_BUILD_DIR
  - go get github.com/badges/buckler
  - export SYMFONY__buckler_bin_path=$GOPATH/bin/buckler

script:
  - bin/phpunit
  
notifications:
  email:
    - liuggio@gmail.com
