language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

services:
  - redis-server

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer selfupdate

install:
  - composer update

script:
  - bin/phpunit -v
  
notifications:
  email:
    - liuggio@gmail.com
