imports:
    - { resource: config_dev.yml }

parameters:
    # for functional test
    image_creator.class: PUGX\BadgeBundle\Tests\Controller\FakeImageCreator

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
