pugx_badge:
    resource: "@PUGXBadgeBundle/Controller/"
    type:     annotation
    prefix:   /

pugx_badge_packagist:
    path: /packages/{repository}
    host: "packagist.org"
    schemes:  [https]
    requirements:
      repository: "[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+"

pugx_badge_shieldio:
    path: /badge/{vendor}-{value}-{color}.{extension}
    host: "img.shields.io"
    requirements:
      vendor: "[A-Za-z0-9_.-]+"
      value:  "[A-Za-z0-9_.-]+"

redirects:
    resource: "@PUGXBadgeBundle/Resources/config/routing/routing_redirects.yml"

aliases:
    resource: "@PUGXBadgeBundle/Resources/config/routing/routing_aliases.yml"
